---
title: "Exploratory Data Analysis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse) 
library(dplyr)
library(dslabs)
library(ggplot2)
library(lubridate) 
library(caret)
library(HistData)
library(Lahman)
library(purrr)
library(pdftools)
library(broom)
library(stringr)
library(tidyr)
library(readr)
```


## Exploratory Data Analysis
```{r}
dat <- read_csv('./data/train.csv')
var_explain <- read_csv('./data/var_explain.csv')
var_explain
glimpse(dat)


dat$Class<-as.factor(dat$depressed) # convert class to factor
levels(dat$Class) <- c('not_depressed', 'depressed') # names of factors
summary(dat$Class)

```


```{r}
head(summary(dat))
```

```{r}
depressed_sub <- dat %>% filter(depressed == 1)
nrow(depressed_sub)
depressed_percent <- nrow(depressed_sub)/nrow(dat)
depressed_percent

prop.table(table(dat$depressed))
# EDA
ggplot(data = dat, aes(fill = Class)) +geom_bar(aes(x = Class))
```
```{r}
dat_depressed <- dat %>% filter(depressed == 1)
dat_notDepressed <- dat %>% filter(depressed == 0)
```


#### Missing Data
```{r}
#check for missing data
anyNA(dat)
sum(is.na(dat))
col_NA <- colnames(dat)[colSums(is.na(dat)) > 0]
col_NA
```

```{r}
#look at rows with missing data
dat_NA <- dat[!complete.cases(dat), ]
nrow(na.omit(dat))
#look at missing pattern
library(ggmice)
plot_pattern(dat[, col_NA])
```

```{r}
for(i in 1:length(col_NA)){
  dat[col_NA[i]][is.na(dat[col_NA[i]])] <- round(sum(dat[col_NA[i]], na.rm=TRUE)/nrow(dat))
}
anyNA(dat)
```

```{r}
cols <- colnames(dat)
cols
library(Hmisc)
hist.data.frame(dat)
```

#### Examine continuous covariates
```{r}
#family factors
pairs(depressed ~ age + children + hhsize + edu + hh_totalmembers + hh_children, dat)

#socio-economic indicating factors
pairs(depressed ~ cons_nondurable + asset_savings + cons_allfood + cons_med_total + cons_ed + cons_social + ent_total_cost, dat)

# life-style/financial factors
pairs(depressed ~ fs_adskipm_often + fs_meat + med_portion_sickinjured + ed_sch_missedpc + durable_investment, dat)
```


```{r}
dat_old <- dat
# Interested/understandable factors
cov <- c("age", "children", "hhsize", "edu" , "hh_totalmembers", "hh_children", "cons_nondurable", "asset_savings", "cons_allfood", "cons_med_total", "cons_ed", "cons_social", "ent_total_cost", "fs_adskipm_often", "fs_meat", "med_portion_sickinjured", "ed_sch_missedpc", "durable_investment", "femaleres", "married", "depressed")

dat <- dat[, cov]

hist.data.frame(dat)
```


```{r}
library(glmnet)
library(vip)
#define outcome variable
y <- dat[,"depressed"] |> as.matrix()
#define matrix of predictor variables
x <- dat[, c("age", "children", "hhsize", "edu" , "hh_totalmembers", "hh_children", "cons_nondurable", "asset_savings", "cons_allfood", "cons_med_total", "cons_ed", "cons_social", "ent_total_cost", "fs_adskipm_often", "fs_meat", "med_portion_sickinjured", "ed_sch_missedpc", "durable_investment", "femaleres", "married")] |> as.matrix()
elasticnet.mod = glmnet(x,y,alpha=0.5,family="binomial")
vip(elasticnet.mod, num_features=10, geom = "point")
```

```{r}
ggplot(dat, aes(age, depressed, color=factor(femaleres))) +
  stat_smooth(method="loess", formula=y~x,
              alpha=0.2, size=2, aes(fill=factor(femaleres))) +
  geom_point(position=position_jitter(height=0.03, width=0)) +
  xlab("Age") + ylab("depressed")
```

## Regression - Association
```{r}
mod_log <- glm(depressed ~ age + children + hhsize+edu + hh_totalmembers+ hh_children+ cons_nondurable+ asset_savings + cons_allfood+ cons_med_total+ cons_ed+ cons_social+ ent_total_cost+ fs_adskipm_often  + fs_meat + med_portion_sickinjured+ ed_sch_missedpc+ durable_investment+ femaleres + married, data = dat, family = "binomial")
summary(mod_log)

# Influence plot
library(car)
par(mfrow=c(1,1))
influencePlot(mod_log,col="red")
```

```{r}
covMatrix <- vcov(mod_log)
corrMatrix <- cov2cor(covMatrix)
head(corrMatrix) 
```


```{r}
#up sampling for imbalanced data
set.seed(260)
datdown <- downSample(x=dat[, -which(names(dat) == "depressed")], y=dat$depressed)
prop.table(table(datdown$y))

#ROSE algorithm
library(ROSE)
drose <- ROSE(depressed ~ ., N = 1900, data = dat, seed = 260)$data
table(drose$depressed)
```

```{r}
mod_log <- glm(depressed ~ age + children + hhsize + edu + cons_nondurable+ asset_savings + cons_ed+ cons_social+ ent_total_cost+ fs_adskipm_often  + fs_meat + med_portion_sickinjured+ ed_sch_missedpc+ durable_investment+ femaleres + married, data = drose, family = "binomial")
summary(mod_log)

influenceIndexPlot(mod_log)
```

```{r}
library(corrplot)
correlations <- cor(dat[, -12], use = "pairwise.complete.obs")
corrplot(correlations, method='number')
corrplot.mixed(correlations,upper = "circle", lower = "number", tl.col = "black", tl.pos = "lt") 
```



```{r}
summary(mod_log)$coefficients
library(pROC)
predprob <- predict(mod_log,type=c("response")) 
roccurve <- roc(drose$depressed ~ predprob)
plot(roccurve,col="red")
roccurve

library(rpart)
#build decision tree models
tree.rose <- rpart(depressed ~ ., data = drose)
pred.tree.rose <- predict(tree.rose, newdata = drose)
roc.curve(drose$depressed, pred.tree.rose)
```


```{r}
#calculate and intepret the coefficients the odds ratio and 95% CI
exp(cbind(OR = coef(mod_log), confint(mod_log)))
```

We can interpret these coefficients in terms of odds ratios. For example, for a one unit increase in the number of children one has, the odds of being depressed (versus not being depressed) increase by a factor of 1.1225961, on average, holding all other covariates fixed. 









